strategy:
  max_consolidation_range_pct: 5.0      
  max_consolidation_period: 20          
  stop_position_inside_box: 0.5         
  max_sl_risk_pct: 2.0                  
  min_close_pct_beyond_box: 1.0         
  max_wick_length_on_breakout_pct: 0.5  
  min_volume_increase_ratio: 1.5        
  req_price_beyond_ema20: true          
  prev_expansion_phase_return_pct: 10.0 
  expansion_lookback_period: 40

trade_management:
  ema_stoploss_period: 200
  target_rr_ratio: 2.0
  trailing_sl_pct: 5.0

portfolio:
  initial_capital: 1000000
